title: KANG SURA
description: Occupational Therapist
site_title: 'KANG SURA'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: KANGSURA
blog_url: Not_yet
email: surakang7410@gmail.com
keybase_username: Not_yet
twitter_username: Not_yet
reddit_username: Not_yet

# absolute or relative1
profile_picture: assets/images/profile_image.jpg

# Google Analytics ID
google_analytics: 
