title: KANG SURA
description: Occupational Therapist
site_title: 'KANG SURA'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: KANGSURA
blog_url: -
email: surakang7410@gmail.com
keybase_username: -
twitter_username: -
reddit_username: -

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
