title: KANG SURA
description: Occupational Therapist
site_title: 'KANG SURA'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: KANGSURA
blog_url: KANGSURA_not_yet
email: surakang7410@gmail.com
keybase_username: KANGSURA_not_yet
twitter_username: KANGSURA_not_yet
reddit_username: KANGSURA_not_yet

# absolute or relative
profile_picture: assets/images/profile_image.jpg

# Google Analytics ID
google_analytics: 
